# Generated by Django 5.1.7 on 2025-04-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabolous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='summary',
            field=models.CharField(default='No summary provided', max_length=50),
        ),
    ]
